
// export const ProductData = [
// {
//   id: 1,
//   name: "cartera bahamas",
//   description: "lorem ipsum",
//   category: "RIÑONERAS",
//   colors: { color1: "#00000", color2: "#00000", color1: "#00000" },
//   price: 75000,
//   images: {
//     img1: "/home-product-1.png",
//     img2: "/home-product-1.png",
//     img3: "/home-product-1.png",
//     img4: "/home-product-1.png",
//   },
//   stock: 10,
//   featured: true,
// },
//   {
//     id: 1,
//     name: "cartera bahamas",
//     description: "lorem ipsum",
//     category_id: 11,
//     colors: { color1: "#00000", color2: "#00000", color1: "#00000" },
//     price: 75000,
//     images: {
//       img1: "/home-product-1.png",
//       img2: "/home-product-1.png",
//       img3: "/home-product-1.png",
//       img4: "/home-product-1.png",
//     },
//     stock: 10,
//     featured: true,
//   },
//   {
//     id: 2,
//     name: "bolso japon",
//     description: "lorem ipsum",
//     category_id: 8,
//     colors: { color1: "#00000", color2: "#00000", color1: "#00000" },
//     price: 75000,
//     images: {
//       img1: "/home-product-1.png",
//       img2: "/home-product-1.png",
//       img3: "/home-product-1.png",
//       img4: "/home-product-1.png",
//     },
//     stock: 10,
//     featured: true,
//   },
//   {
//     id: 3,
//     name: "bandolera kenny",
//     description: "lorem ipsum",
//     category_id: 9,
//     colors: { color1: "#00000", color2: "#00000", color1: "#00000" },
//     price: 75000,
//     images: {
//       img1: "/home-product-1.png",
//       img2: "/home-product-1.png",
//       img3: "/home-product-1.png",
//       img4: "/home-product-1.png",
//     },
//     stock: 10,
//     featured: true,
//   },
//   {
//     id: 4,
//     name: "cartera bahamas",
//     description: "lorem ipsum",
//     category_id: 10,
//     colors: { color1: "#00000", color2: "#00000", color1: "#00000" },
//     price: 75000,
//     images: {
//       img1: "/home-product-1.png",
//       img2: "/home-product-1.png",
//       img3: "/home-product-1.png",
//       img4: "/home-product-1.png",
//     },
//     stock: 10,
//     featured: true,
//   },
//   {
//     id: 5,
//     name: "billetera diana",
//     description: "lorem ipsum",
//     category_id: 12,
//     colors: { color1: "#00000", color2: "#00000", color1: "#00000" },
//     price: 75000,
//     images: {
//       img1: "/home-product-1.png",
//       img2: "/home-product-1.png",
//       img3: "/home-product-1.png",
//       img4: "/home-product-1.png",
//     },
//     stock: 10,
//     featured: true,
//   },
//   {
//     id: 6,
//     name: "morral marley",
//     description: "lorem ipsum",
//     category_id: 13,
//     colors: { color1: "#00000", color2: "#00000", color1: "#00000" },
//     price: 75000,
//     images: {
//       img1: "/home-product-1.png",
//       img2: "/home-product-1.png",
//       img3: "/home-product-1.png",
//       img4: "/home-product-1.png",
//     },
//     stock: 10,
//     featured: true,
//   },
// ];

// export const CategoryData = [
  //   {
  //     category: "Carteras",
  //     link: "/Productos",
  //     image: "/home-product-1.png",
  //   },
  //   {
  //     category: "Mochilas",
  //     link: "/Productos",
  //     image: "/home-product-3.png",
  //   },
  //   {
  //     category: "Manos Libres",
  //     link: "/Productos",
  //     image: "/home-product-2.png",
  //   },
  //   {
  //     category: "Bandoleras",
  //     link: "/Productos",
  //     image: "/home-product-2.png",
  //   },
  //   {
  //     category: "Billeteras",
  //     link: "/Productos",
  //     image: "/home-product-2.png",
  //   },
  //   {
  //     category: "Monederos",
  //     link: "/Productos",
  //     image: "/home-product-2.png",
  //   },
  // ];